services:
  - type: web
    name: chat-backend
    env: node
    plan: free
    buildCommand: bash build-backend.sh
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        fromService:
          type: web
          name: chat-frontend
          property: host

  - type: web
    name: chat-frontend
    env: node
    plan: free
    buildCommand: bash build-frontend.sh
    startCommand: bash start-frontend.sh
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: chat-backend
          property: host
